// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.22408 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Egais.Entities.EGCommonEnum</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Egais.Entities.EGCommonEnum {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    using Egais.Entities.EGCommon;
    

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=false)]
    public enum PlaceEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1186240")]
        Item1186240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1186244")]
        Item1186244,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1186245")]
        Item1186245,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1710969")]
        Item1710969,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=false)]
    public enum ModeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=false)]
    public enum TypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("022")]
        Item022,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("104")]
        Item104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("105")]
        Item105,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("111")]
        Item111,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("115")]
        Item115,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("118")]
        Item118,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("119")]
        Item119,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("120")]
        Item120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("121")]
        Item121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("122")]
        Item122,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("123")]
        Item123,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("125")]
        Item125,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("126")]
        Item126,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("127")]
        Item127,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("129")]
        Item129,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("135")]
        Item135,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("136")]
        Item136,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("137")]
        Item137,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("139")]
        Item139,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("141")]
        Item141,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("142")]
        Item142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("143")]
        Item143,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("144")]
        Item144,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("145")]
        Item145,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("146")]
        Item146,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("147")]
        Item147,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("148")]
        Item148,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("149")]
        Item149,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("150")]
        Item150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("151")]
        Item151,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("152")]
        Item152,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("153")]
        Item153,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("154")]
        Item154,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("155")]
        Item155,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("156")]
        Item156,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("157")]
        Item157,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("158")]
        Item158,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("159")]
        Item159,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("160")]
        Item160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("161")]
        Item161,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("162")]
        Item162,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("163")]
        Item163,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("164")]
        Item164,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("165")]
        Item165,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("166")]
        Item166,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("167")]
        Item167,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("168")]
        Item168,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("169")]
        Item169,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("202")]
        Item202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("203")]
        Item203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("204")]
        Item204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("205")]
        Item205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("206")]
        Item206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("207")]
        Item207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("208")]
        Item208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("209")]
        Item209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("211")]
        Item211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("212")]
        Item212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("213")]
        Item213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("214")]
        Item214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("215")]
        Item215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("216")]
        Item216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("217")]
        Item217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("218")]
        Item218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("219")]
        Item219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")]
        Item221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("222")]
        Item222,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("223")]
        Item223,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("224")]
        Item224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("225")]
        Item225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("226")]
        Item226,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("227")]
        Item227,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("228")]
        Item228,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("229")]
        Item229,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")]
        Item230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("231")]
        Item231,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("232")]
        Item232,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("233")]
        Item233,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("234")]
        Item234,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("235")]
        Item235,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("170")]
        Item170,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("171")]
        Item171,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("172")]
        Item172,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("173")]
        Item173,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("174")]
        Item174,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("175")]
        Item175,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("176")]
        Item176,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("177")]
        Item177,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("178")]
        Item178,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("179")]
        Item179,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("180")]
        Item180,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("181")]
        Item181,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("182")]
        Item182,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("183")]
        Item183,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("184")]
        Item184,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("185")]
        Item185,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("236")]
        Item236,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("237")]
        Item237,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("238")]
        Item238,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("239")]
        Item239,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("240")]
        Item240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("241")]
        Item241,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("242")]
        Item242,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("243")]
        Item243,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("244")]
        Item244,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("245")]
        Item245,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("246")]
        Item246,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=false)]
    public enum TypeWriteOff {
        
        /// <remarks/>
        Пересортица,
        
        /// <remarks/>
        Недостача,
        
        /// <remarks/>
        Уценка,
        
        /// <remarks/>
        Порча,
        
        /// <remarks/>
        Потери,
        
        /// <remarks/>
        Проверки,
        
        /// <remarks/>
        Арест,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Иные цели")]
        Иныецели,
        
        /// <remarks/>
        Реализация,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Производственные потери")]
        Производственныепотери,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=true)]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarkCodeInfoType", Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    public partial class MarkCodeInfoType : System.ComponentModel.INotifyPropertyChanged {
        
        private List<string> markCodeField;
        
        private static System.Xml.Serialization.XmlSerializer serializer;
        
        public MarkCodeInfoType() {
            this.markCodeField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MarkCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> MarkCode {
            get {
                return this.markCodeField;
            }
            set {
                if ((this.markCodeField != null)) {
                    if ((markCodeField.Equals(value) != true)) {
                        this.markCodeField = value;
                        this.OnPropertyChanged("MarkCode");
                    }
                }
                else {
                    this.markCodeField = value;
                    this.OnPropertyChanged("MarkCode");
                }
            }
        }
        
        private static System.Xml.Serialization.XmlSerializer Serializer {
            get {
                if ((serializer == null)) {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(MarkCodeInfoType));
                }
                return serializer;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current MarkCodeInfoType object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize() {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally {
                if ((streamReader != null)) {
                    streamReader.Dispose();
                }
                if ((memoryStream != null)) {
                    memoryStream.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes workflow markup into an MarkCodeInfoType object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output MarkCodeInfoType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out MarkCodeInfoType obj, out System.Exception exception) {
            exception = null;
            obj = default(MarkCodeInfoType);
            try {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool Deserialize(string xml, out MarkCodeInfoType obj) {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }
        
        public static MarkCodeInfoType Deserialize(string xml) {
            System.IO.StringReader stringReader = null;
            try {
                stringReader = new System.IO.StringReader(xml);
                return ((MarkCodeInfoType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally {
                if ((stringReader != null)) {
                    stringReader.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Serializes current MarkCodeInfoType object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception) {
            exception = null;
            try {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e) {
                exception = e;
                return false;
            }
        }
        
        public virtual void SaveToFile(string fileName) {
            System.IO.StreamWriter streamWriter = null;
            try {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally {
                if ((streamWriter != null)) {
                    streamWriter.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes xml markup from file into an MarkCodeInfoType object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output MarkCodeInfoType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out MarkCodeInfoType obj, out System.Exception exception) {
            exception = null;
            obj = default(MarkCodeInfoType);
            try {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool LoadFromFile(string fileName, out MarkCodeInfoType obj) {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }
        
        public static MarkCodeInfoType LoadFromFile(string fileName) {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally {
                if ((file != null)) {
                    file.Dispose();
                }
                if ((sr != null)) {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.22414")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://fsrar.ru/WEGAIS/CommonEnum", IsNullable=false)]
    public enum TypeChargeOn {
        
        /// <remarks/>
        Пересортица,
        
        /// <remarks/>
        Излишки,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Продукция, полученная до 01.01.2016")]
        Продукцияполученнаядо01012016,
        
        /// <remarks/>
        Производство_Сливы,
    }
}
